apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  labels:
    app: redis-server
spec:
  selector:
    matchLabels:
      app: redis-server
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
      - name: redis-server
        image:  redis:latest
        ports:
        - containerPort:  6379
          name: redis-port
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
spec:
  selector:
    app: redis-server
  type: NodePort
  ports:
  - name: redis-server
    protocol: TCP
    port: 6379
    targetPort: 6379 
    nodePort: 30379 