apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-persistent-volumes
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
  storageClassName: my-storage